FROM kwierman/hep-dl
CMD /bin/bash
#CMD "cd /data \
#  && rsync ec2-54-213-91-246.us-west-2.compute.amazonaws.com/data.tar.gz /tmp/data.tar.gz\
#  && rsync ec2-54-213-91-246.us-west-2.compute.amazonaws.com/test.root
#"